# Generated by Django 3.2.8 on 2021-10-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211027_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
